### PR TITLE
move archive keyring out of global trust path

### PR DESCRIPTION
**Pull request by anarcat**
The [repository instructions][1] have been changed to avoid writing
third-party keyring files to the global trust anchors (in
`/etc/apt/trusted-gpg.d`) and instead write those to a more neutral
location (`/usr/share/keyrings`, alongside other keyring files).

[1]: https://wiki.debian.org/RepositoryInstructions

The downside of this change is that the key fingerprint isn't
validated directly through this process. But considering that
validation of the key is anchored through HTTPS validation in the
first place, we do not *really* lose anything by moving that to the
`.gpg` file transfer: that file's integrity is still checked through
HTTPS. Furthermore, not storing the explicit fingerprint here will
make future key rotations easier as they will not require
documentation updates.

Note that this change will also require a change in the
`grml-debian-keyring` package to install the keyring file in the new
location. If that package does not install a `.sources` or `.list`
file, that move will also break existing configurations, so a NEWS
entry might be in order as well.

This is related to the [proposed website documentation change][2]

[2]: https://github.com/grml/grml.org/pull/21

### CODE REVIEW

**Comment by mika** [comment]
I looked into this and its integration is trickier than expected, since we a) don't ship `/etc/apt/sources.list.d/grml.sources` nor `/etc/apt/sources.list.d/grml.list` via grml-debian-keyring or any other package and b) have to support Debian releases older then Debian/stretch and c) don't have repositories matching Debian releases and/or Grml releases.

I've tested the following changes with Debian jessie and Debian stretch based systems and AFAICT it looks good (if everything works 100% fine will be known only once it's available in grml-testing):

  https://github.com/grml/grml-debian-keyring/commits/mika/wip

@anarcat - can you please review my changes and whether they make sense for you as well?
I'd appreciate review by the other Grml devs as well (@evgeni @formorer @ft @jkirk )!

**Comment by anarcat** [comment]
hi @mika ! 

thanks for working on this, it's hugely appreciated. :) it's true it must be tricky to support older release: I basically completely ignored that problem and assumed we were supporting only stretch and later, which makes things easier, but it's true that it cuts us off from a large part of the current installs... 

that said, it seems to me the relevant commits in your branch are: https://github.com/grml/grml-debian-keyring/commit/9f14a657b3ee0a3316f0829100b6381299d96010
and https://github.com/grml/grml-debian-keyring/commit/1323d48e442a93c81616ec0dd2268427043191be, the latter being mine. the rest is basically documentation. I've added a comment on the first one regarding the method chosen to detect if apt supports the functionality we need... other than that, the backwards-compatible hack seems sound.

i would advise, however, to ship the `.list` file. the concern i have with the approach you have chosen is adoption: because it's "opt-in", most users will not actually remove their trusted-gpg.d file and will keep on using the deprecated keyring. this will make future rotations harder and basically defeats the whole point of standardizing this package. it also creates a strange situation where users on wheezy/jessie *will* have their `trusted-gpg.d` file installed and when they upgrade to stretch, the file will be kept there, still orphaned.

also, in my opinion, shipping the sources.list file should be a standard part of any -archive-keyring package. there are compatibility issues to think about, for sure, but i think those can be worked out with symlinks the way you proceeded. nail this correctly in grml-archive-keyring, and we can take it as an example that we can standardize across debian. who knows, maybe we could have some debhelper script to manage all that stuff for us eventually. ;)

so, my TL;DR: great work, but I would push it even further and actually ship sources.list. let me know if you want me to patch together something.

**Comment by mika** [comment]
Thanks for your review, appreciated!

I'm aware of the problems of this "opt-in" approach, though shipping a .list or .sources file with the *keyring* package feels wrong to me, for two reasons:

1) What repository does the user actually want? grml-stable only? grml-testing? Both? Something else (grml-live)? That choice should be left to the user and if we ever go that route we should probably provide different packages according to the needs then.

2) I assume that plenty of users out there who use the grml-repository in any way control their apt configuration with some kind of config management, and they might even end in duplicated apt `.list` files if we start shipping that, so also then they would have to do something about it.

If we should have spare time to think about this in more detail (e.g. by providing grml-apt-stable + grml-apt-testing packages, which create /etc/apt/sources.list.d/* files during installation and depending on grml-debian-keyring package) then I'm happy to revisit this again, but we're in lack of humanpower currently and trying to get a new release out. :)

**Comment by anarcat** [comment]
interesting point - i guess the proper way forward then would be to create a separate package, indeed.

i would say, however, that `sources.list` files are configurable, as any debian package config file. so it could have sane defaults (e.g. "stable") that could get overriden by the user any way they choose...

but yeah, please go ahead with the release, this can be fixed later too.

**Pull request merged**
